import ReactQueryProvider from "@/components/providers/query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { GlobalAlert } from "@/components/ui/global-alert";
import { Toaster } from "@/components/ui/sonner";
import { AlertProvider } from "@/context/alert-context";
import { ErrorProvider } from "@/context/error-context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { TooltipProvider } from "@/components/ui/tooltip";
import Script from "next/script";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mealz & Dealz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.className}>
      <Script id="fb-sdk-init" strategy="afterInteractive">
        {`
          window.fbAsyncInit = function() {
            FB.init({
              appId      : ${process.env.FACEBOOK_ID},
              xfbml      : true,
              version    : 'v22.0'
            });
          };
        `}
      </Script>

      {/* Facebook SDK script */}
      <Script
        strategy="afterInteractive"
        async
        defer
        crossOrigin="anonymous"
        src="https://connect.facebook.net/en_US/sdk.js"
      />
      <body
        suppressHydrationWarning
        // className={`${openSans.variable}`}
      >
        <ReactQueryProvider>
          <TooltipProvider>
            <AlertProvider>
              <ErrorProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="light"
                  enableSystem
                  disableTransitionOnChange
                >
                  {children}
                  <Toaster />
                  <GlobalAlert />
                </ThemeProvider>
              </ErrorProvider>
            </AlertProvider>
          </TooltipProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
