import ReactQueryProvider from "@/components/providers/query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { GlobalAlert } from "@/components/ui/global-alert";
import { Toaster } from "@/components/ui/sonner";
import { AlertProvider } from "@/context/alert-context";
import { ErrorProvider } from "@/context/error-context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";
import { LocationProvider } from "@/context/location-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lead Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.className}>
      <body suppressHydrationWarning>
        <ReactQueryProvider>
          <LocationProvider>
            <TooltipProvider>
              <AlertProvider>
                <ErrorProvider>
                  <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem
                    disableTransitionOnChange
                  >
                    {children}
                    <Toaster />
                    <GlobalAlert />
                  </ThemeProvider>
                </ErrorProvider>
              </AlertProvider>
            </TooltipProvider>
          </LocationProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
